# Project information
site_name: Rotterdam wet en regelgeving
site_url: 'https://wetboek.rotterdam.nl/'
site_description: 'Wet en regelgeving van Rotterdam roleplay'
site_author: 'Rotterdam'

# Copyright
copyright: Copyright &copy; 2019 - 2022 Tedeapolis

# Repository
repo_url: 'https://github.com/Alem569/wetboek/'
repo_name: 'wetboek'
edit_uri: 'https://github.com/Alem569/wetboek/blob/master/docs/'

# Google Analytics
google_analytics: ['UA-167800475-3', 'wetboek.rotterdam.nl']

# Congiguration
theme:
  name: material
#   features:
#     - navigation.tabs
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  favicon: img/logoTedeapolis.png
  logo: img/logoTedeapolis.webp
  custom_dir: docs/overrides
  language: nl
plugins:
  - git-revision-date-localized:
      type: timeago
      time_zone: Europe/Amsterdam
      locale: nl
      fallback_to_build_date: false
  - search:
      lang: nl
markdown_extensions:
  - admonition
  - attr_list
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tables.js
nav:
  - Home: index.md
  - Algemene Plaatselijke Verordening: apv.md
  - Wetboek: wetboek.md
  - Risicogebieden: risico-gebieden.md
  - Douanegebieden: douanegebieden.md
  - NOTAM: notam.md
  - Belastingen: belastingen.md
  - Regelement voor de rechtspraak: rechtspraak.md
  - Streamen op Rotterdam: streamen.md
  - Offroad Voertuigen: offroadvoertuigen.md
  - Kosten:
    - Advocatuur: kosten/advocatuur.md
    - Ambulance: kosten/ambulance.md
    - ANWB: kosten/anwb.md
    - Politie: kosten/politie.md
    - Vliegschool: kosten/vliegschool.md
